

package com.ycr.Controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

import com.ycr.DAO.UserDao;
import com.ycr.Model.Categorie;
import com.ycr.Model.User;
import com.ycr.Repository.UserRepository;;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserDao userDao;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String pseudo
			, @RequestParam String password) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setPseudo("a");
		n.setPassword("a");
		userDao.save(n);
		return "Saved";
	}
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		return userDao.findAll();
	}
}

